# Generated by Django 2.2.7 on 2021-05-14 19:39

from django.db import migrations, models
import django.utils.timezone
import tweet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100, null=True)),
                ('object_name', models.CharField(max_length=100, null=True)),
                ('x_min', models.IntegerField(null=True)),
                ('x_max', models.IntegerField(null=True)),
                ('y_min', models.IntegerField(null=True)),
                ('y_max', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_path', models.ImageField(null=True, upload_to=tweet.models.upload_to, verbose_name='Image')),
            ],
        ),
    ]
