# Generated by Django 2.2.7 on 2021-05-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
