# Generated by Django 2.2.7 on 2021-05-14 20:02

from django.db import migrations, models
import tweet.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_auto_20210515_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='xml_path',
            field=models.ImageField(null=True, upload_to=tweet.models.upload_to2, verbose_name='XML'),
        ),
    ]
